apiVersion: v1
kind: Service
metadata:
  name: ibkr-backend
  namespace: ibkr
spec:
  type: LoadBalancer
  selector:
    app: ibkr-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
