apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-gateway-restart
  namespace: ibkr
subjects:
  - kind: ServiceAccount
    name: backend-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-gateway-restart
