apiVersion: v1
kind: Service
metadata:
  name: ibkr-frontend
  namespace: ibkr
spec:
  type: LoadBalancer
  selector:
    app: ibkr-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
