apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibkr-frontend
  namespace: ibkr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibkr-frontend
  template:
    metadata:
      labels:
        app: ibkr-frontend
    spec:
      containers:
        - name: frontend
          image: cvvz/ibkr-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ibkr-frontend
  namespace: ibkr
spec:
  type: LoadBalancer
  selector:
    app: ibkr-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
