apiVersion: apps/v1
kind: Deployment
metadata:
  name: ib-gateway
  namespace: ibkr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ib-gateway
  template:
    metadata:
      labels:
        app: ib-gateway
    spec:
      containers:
        - name: ib-gateway
          image: cvvz/ib-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7496
              name: ib-api
            - containerPort: 5900
              name: vnc
          env:
            - name: VNC_PORT
              value: "5900"
          volumeMounts:
            - name: ib-data
              mountPath: /root/ibkr
      volumes:
        - name: ib-data
          persistentVolumeClaim:
            claimName: ib-gateway-data
