apiVersion: v1
kind: Service
metadata:
  name: ib-gateway-novnc
  namespace: ibkr
spec:
  type: LoadBalancer
  selector:
    app: ib-gateway-novnc
  ports:
    - name: http
      port: 6080
      targetPort: 6080
